server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms-usuarios
          # Ruta directa e infalible
          uri: https://imaginative-caring-production.up.railway.app
          predicates:
            - Path=/api/usuarios/**
          filters:
            # Este filtro es clave: le dice a Railway que vamos al microservicio correcto
            - SetRequestHeader=Host, imaginative-caring-production.up.railway.app

eureka:
  client:
    service-url:
      defaultZone: https://jdm-70-production.up.railway.app/eureka/
    register-with-eureka: true
    fetch-registry: true