server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          # APAGAMOS EL PILOTO AUTOMÁTICO. Ahora solo usará la ruta que escribimos abajo.
          enabled: false
      routes:
        - id: ruta-directa-usuarios
          uri: https://imaginative-caring-production.up.railway.app
          predicates:
            - Path=/api/usuarios/**
          filters:
            # Engañamos a la seguridad de Railway para que nos deje pasar
            - SetRequestHeader=Host, imaginative-caring-production.up.railway.app

eureka:
  client:
    service-url:
      defaultZone: https://jdm-70-production.up.railway.app/eureka/
    register-with-eureka: true
    fetch-registry: true