spring:
  application:
    name: ms-usuarios
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql.railway.internal:3306/railway}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: https://jdm-70-production.up.railway.app/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: ${RAILWAY_PRIVATE_DOMAIN}

server:
  port: ${PORT:8081}