spring:
  application:
    name: ms-usuarios
  datasource:
    # Si Railway no encuentra una variable, usará lo que está después de los dos puntos (localhost)
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/foro_usuarios_db}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      # Si Railway no tiene esta variable, buscará en localhost:8761
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true

server:
  # Railway suele inyectar una variable llamada PORT, si no, usa el 8081
  port: ${PORT:8081}